### ISSUE TITLE
Let WordPress core handle .pot language file location

### ISSUE THREAD

**Issue by cowgill** [AppThemes/Updater#12]
We no longer need to declare the .pot locale nor use `load_textdomain();`. WordPress core does this automatically in [wp-admin/includes/plugin.php](https://github.com/WordPress/WordPress/blob/e4abc1ecbf04503bc53b21f58c72d7108d4f55f5/wp-admin/includes/plugin.php#L127-L134).

Instead, just add the `Domain Path:` to the plugin's header file as noted on the [WordPress Developer Intl page](https://developer.wordpress.org/plugins/internationalization/how-to-internationalize-your-plugin/#domain-path).

`Domain Path: /languages`

**Comment by cowgill** [comment]
@meloniq was correct. After doing some testing, the `load_textdomain()` and `load_plugin_textdomain()` code is still required. I've enhanced it further and will write up so documentation on best practices for all our products.

**Comment by meloniq** [comment]
![Uploading WP_20160813_12_28_38_Pro.jpg…]()

From prelection on WCMSK :) - but only for projects stored on WP.org

**Comment by cowgill** [comment]
@meloniq, your image didn't upload.

**Comment by meloniq** [comment]
@cowgill I have edited my comment above, image uploaded :)

**Comment by cowgill** [comment]
@meloniq thanks. That's good news so eventually we can remove that extra code!
