### ISSUE TITLE
Automatic update/notification not working

### ISSUE THREAD

**Issue by Jomark** [AppThemes/Updater#15]
Customers reported https://forums.appthemes.com/report-vantage-bugs/no-version-update-98268/#post413750 and https://forums.appthemes.com/appthemes-updater-plugin/updater-not-finding-updates-97315/ that the Updater plugin no longer works. 

I have tested it on my Vantage site by loading version 4.1.0 and there is no notification for update to version 4.1.2.

Kindly check on this. Thanks.

**Comment by Jomark** [comment]
If you can find time, kindly check on this.

**Comment by dikiyforester** [comment]
I'll check this!

**Comment by dikiyforester** [comment]
Please keep in mind Vantage installs prior 4.0.0 versions can't be upgraded to 4.0.0+ usinf AppThemes Updater plugin by purpose. 

https://github.com/AppThemes/appthemes.com/blob/master/wp-content/themes/at-api/includes/utils.php#L81-L83

**Comment by dikiyforester** [comment]
@Jomark could you check the Vantage folder name on your test site. It needs to be `appthemes-vantage`.

**Comment by Jomark** [comment]
@dikiyforester I have tested it before but will retest and update you then.

**Comment by Jomark** [comment]
Another set of customers are reporting this issue, Yes my test site's theme folder name is appthemes-vantage and still it did not trigger update modification. I have loaded VantageVersion: 4.1.0 to test it out.

**Comment by Jomark** [comment]
A customer PMd  me his site with Vantage 4.0.1 and Updater plugin. Still no notification for theme update to the latest version . I will send you the login credentials via slack.

**Comment by dikiyforester** [comment]
That is very strange. I see updates if theme located in `vantage` directory, but when I rename it to `appthemes-vantage` it disappears.

I think something wrong with appthemes.com API.
I would start to dig from this place https://github.com/AppThemes/appthemes.com/blob/master/wp-content/plugins/at-products/class-theme-api.php#L66

I will check it out ASAP

**Comment by dikiyforester** [comment]
@Jomark I've fixed issue on the server but seems like user still not able to update his theme.
I've used his API key on my site and can confirm that it doesn't work while my API Key works fine.

Please check the following:
1. Customer API key is correct (check it here https://my.appthemes.com/api-key/)
2. The customer has an active subscription to Vantage theme updates or Club.

Let me know and I'll continue research.

Thanks!

**Comment by Jomark** [comment]
@dikiyforester I will ask the customer and update you then.

**Comment by dikiyforester** [comment]
Thank you for the update!

I will investigate it more.

**Comment by dikiyforester** [comment]
At the moment I can confirm that my Key works fine on the customer's site, but customer's key does not.

![2018-09-26 11-53-44](https://user-images.githubusercontent.com/4242025/46062399-1d39bd80-c183-11e8-8b2f-3787256c9869.png)


Investigating more

**Comment by dikiyforester** [comment]
Issue is fixed via core server update https://github.com/AppThemes/appthemes.com/commit/9717455d92d5d6f426407ab55f57174eb2efd934
