### ISSUE TITLE
Compatibility with WordPress XYZ: Unknown

### ISSUE THREAD

**Issue by meloniq** [AppThemes/Updater#5]
That message happen because WP Info API not return results for products available from our servers...

Consider modifying response, and to not invent our Info API, always end up with 'Compatibility with WordPress XYZ: 100% (according to its author)' ?!

![compatibility-unknown](https://cloud.githubusercontent.com/assets/1211101/5144351/0626f2da-719a-11e4-87fb-8dffce2e25e1.jpg)

**Comment by cowgill** [comment]
I noticed this too. I thought it was trying to read the `Tested up to:` tag from the plugin's `readme.txt` file which it might be doing but we can't do it with our updater plugin. 

We have a few options:

1. Add a new meta field to the Marketplace item's page called, "Tested up to". Sellers will control it from there. Then the updater plugin will need to check against that field. Note: We'll also need to do this for our .com themes.
2. @meloniq suggestion of just saying, "100% according to the author"
3. Do nothing and just leave it as is

I think option 1 is the best choice. I'll just need to add the custom meta field to the Marketplace site first. Then @meloniq can add the check to the updater plugin.

What do you think, @meloniq?

**Comment by cowgill** [comment]
Actually, the easiest choice and to prevent authors from lagging behind each WordPress release, we should just go with option 2.

`100% (according to its author)`

**Comment by meloniq** [comment]
I'll look at the API and available filters, to see what and in which way we can do it in recent WP releases.

**Comment by cowgill** [comment]
Actually, I ended up adding some new fields to support this. That way, authors can keep involved and not let their products fall behind.

https://github.com/AppThemes/appthemes.com/issues/721

**Comment by cowgill** [comment]
Ok, this has been fixed via the above 721 commit. It's live and seems to be working. I'll just need to let sellers know about the fields and how they work once we release v1.4.0 of the Updater plugin.

**Comment by meloniq** [comment]
Cool! Good job! Tested, and its working when item have set the "tested up to" field. :+1:
